version: '3'
volumes:
  tembea_data:
    external: true

services:
  app:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    links:
      - database
    volumes:
      - /usr/app/node_modules
      - ../../:/usr/app
    ports:
      - '5000:5000'
    env_file:
      - ../../.env
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres:postgres@database/tembea
    entrypoint:
      - /usr/app/docker/dev/entrypoint.sh
    command:
      - yarn
      - start:dev
    depends_on:
      - database
  database:
    image: postgres:9.6-alpine
    expose:
      - '5432'
    ports:
      - '5433:5432'
    volumes:
      - tembea_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tembea
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 10s
      retries: 5
